### ISSUE TITLE
Example application not on https

### ISSUE THREAD

**Issue by margaret** [danielhomola/science_flask#2]
Cool project! I think you need to configure SSL certs on the example app in the README — https://ec2-52-215-3-198.eu-west-1.compute.amazonaws.com/

Firefox and Chrome both don't want to connect to it and return this error https://support.mozilla.org/en-US/kb/troubleshoot-SEC_ERROR_UNKNOWN_ISSUER?as=u&utm_source=inproduct

**Comment by danielhomola** [comment]
It's a self-signed SSL so it will show up in any browser exactly as you've described. If you say go ahead at the warning sign, it will lead to a perfectly fine, SSL encrypted website. Didn't want to wait with the release until I get a proper domain and SSL cert for the website but it's coming :)
